INSERT INTO DEPARTAMENTO VALUES(-1,'Financeiro');
INSERT INTO DEPARTAMENTO VALUES(-2,'Comercial');
INSERT INTO FUNCIONARIO(MATRICULA,NOME,DATA_CADASTRO,ID_DEPTO)VALUES('ALFA001','Ana',null,-1);
INSERT INTO FUNCIONARIO(MATRICULA,NOME,DATA_CADASTRO,ID_DEPTO)VALUES('ALFA002','Carlos',null,-1);
INSERT INTO FUNCIONARIO(MATRICULA,NOME,DATA_CADASTRO,ID_DEPTO)VALUES('ALFA003','Maria',null,-2);
INSERT INTO FUNCIONARIO(MATRICULA,NOME,DATA_CADASTRO,ID_DEPTO)VALUES('BETA001','Paulo',null,-2);
INSERT INTO FUNCIONARIO(MATRICULA,NOME,DATA_CADASTRO,ID_DEPTO)VALUES('BETA002','Beatriz',null,-1);
